#!/bin/bash

#!/bin/bash
clear
# validate gradle version
#=======================================================================================================================
SEARCH_STR=somes
ROOT_PROJECT_FOLDER=${PWD%%$SEARCH_STR*}$SEARCH_STR
BASH_PROPERTIES_PATH="$ROOT_PROJECT_FOLDER/sh/bash.properties"
source <(sed 's@\(.*\)\.\(.*\)=@\1_\2=@' $BASH_PROPERTIES_PATH)
GRADLE_VALIDATOR_PATH_SCRIPT_PATHSCRIPT_PATH=$ROOT_PROJECT_FOLDER$GRADLE_VALIDATOR_PATH
source "${GRADLE_VALIDATOR_PATH_SCRIPT_PATHSCRIPT_PATH}"
#=======================================================================================================================
if [[ ${GRADLE_VERSION_IS_VALID} == 0 ]]; then
  exit
fi
#=======================================================================================================================

PROJECT_FLD=$PWD
echo "PROJECT_FLD = $PROJECT_FLD"
cd ../../../

gradle clean build --build-cache -x test -x distTar -x bootDistTar -x distZip -x bootDistZip -x detekt -x checkBestPractices || exit 1

cd $PROJECT_FLD

YML_FLD="dc-banking-dev.yml"
ENV_FLD=".env-dev"
CONTEXT_NAME="ulia-dev"

docker context use $CONTEXT_NAME

docker-compose \
  --file $PROJECT_FLD/$YML_FLD \
  --env-file $PROJECT_FLD/$ENV_FLD \
  down

docker-compose \
  --file $PROJECT_FLD/$YML_FLD \
  --env-file $PROJECT_FLD/$ENV_FLD \
  build

docker-compose \
  --file $PROJECT_FLD/$YML_FLD \
  --env-file $PROJECT_FLD/$ENV_FLD \
  up \
  -d