#!/bin/bash
clear

export IMAGE_PREFIX=test

declare -a PROJECT_MODULES=(
"tests4student/studying"
)

SEARCH_STR=somes
ROOT_PROJECT_FOLDER=${PWD%%$SEARCH_STR*}$SEARCH_STR
BASH_PROPERTIES_PATH="$ROOT_PROJECT_FOLDER/sh/bash.properties"
source <(sed 's@\(.*\)\.\(.*\)=@\1_\2=@' $BASH_PROPERTIES_PATH)
GRADLE_VALIDATOR_PATH_SCRIPT_PATHSCRIPT_PATH=$ROOT_PROJECT_FOLDER$GRADLE_VALIDATOR_PATH
source "${GRADLE_VALIDATOR_PATH_SCRIPT_PATHSCRIPT_PATH}"

if [[ ${GRADLE_VERSION_IS_VALID} == 0 ]]; then
  exit
fi

source <(sed 's@\(.*\)\.\(.*\)=@\1_\2=@' $BASH_PROPERTIES_PATH)
PUSH_SCRIPT_PATH=$ROOT_PROJECT_FOLDER$CREATE_IMAGE_PATH

cd $ROOT_PROJECT_FOLDER
echo "ROOT_PROJECT_FOLDER='$ROOT_PROJECT_FOLDER'"

gradle clean build --build-cache -x test -x distTar -x bootDistTar -x distZip -x bootDistZip -x detekt -x checkBestPractices || exit 1

export TAG_PREFIX=latest
export GIT_REPO_NAME=git2.ulia.com:5555

sudo docker login $GIT_REPO_NAME || exit 1

#=================================================================
# process projects

for gradleApp in "${PROJECT_MODULES[@]}"
do
  export PROJECT_NAME=$gradleApp
  echo "PROJECT_NAME=$PROJECT_NAME; TAG=$IMAGE_PREFIX"
  source "${PUSH_SCRIPT_PATH}" || exit 1
done

echo "##################################################################################################################"
docker image ls
sudo docker logout $GIT_REPO_NAME || exit 1
